CREATE DATABASE SHIRKET

USE SHIRKET

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(50)
)

CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
MKOD NVARCHAR(50) NOT NULL,
SAA NVARCHAR(255) NOT NULL,
VEZIFEID INT REFERENCES VEZIFE(ID),
SALARY MONEY
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(50) NOT NULL
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
BUYPRICE MONEY,
SELLPRICE MONEY
)

CREATE TABLE SATISH(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
ENDIRIM FLOAT,
TARIX DATE
)

INSERT INTO VEZIFE
VALUES('KASSIR')

INSERT INTO FILIAL
VALUES('AXMEDLI')

INSERT INTO MEHSUL
VALUES('COKE',5,10)

INSERT INTO ISCI
VALUES('OBA','QAQA QAQAYEV QAQALAR OGLU' , 1 , 120)

SELECT COUNT(ISCI.ID) 'EMPLOYEE COUNT' FROM ISCI 

SELECT ISCI.SAA,ISCI.SALARY FROM ISCI
ORDER BY SALARY DESC

SELECT BUYPRICE FROM MEHSUL
ORDER BY BUYPRICE DESC

SELECT * FROM SATISH
ORDER BY TARIX ASC

SELECT CONCAT(ISCI.SAA,' ',VEZIFE.VEZIFE) 'ISCI VE VEZIFELERI' FROM ISCI
JOIN VEZIFE
ON ISCI.VEZIFEID = VEZIFE.ID